<?php
    include_once('userMapper.php');
    include_once('tweetMapper.php');
    include_once('trendMapper.php');
    include_once('likeMapper.php');
    include_once('retweetMapper.php');
    include_once('commentMapper.php');
    include_once('followMapper.php');
    include_once('messageMapper.php')
?>